install:
 - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

jobs:
  include:
    - if: NOT tag IS present
      script: l3build check -q -H --show-log-on-error
      name: "Test suite"
    - if: NOT tag IS present
      script: l3build doc -q -H
      name: "Documentation"
    - if: tag IS present
      script: l3build ctan -H --show-log-on-error
      name: "Full CTAN build"

notifications:
  email:
    recipients:
      - latex3-commits@tug.org
    on_success: change
    on_failure: always
    on_start:   never

